# Generated by Django 3.2.13 on 2022-09-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и фамилия')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('question', models.TextField(verbose_name='Вопросы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
