# Generated by Django 3.2.13 on 2022-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(choices=[('ready', 'готовый товар'), ('to order', 'на заказ')], max_length=200, verbose_name='Название'),
        ),
    ]
